# Generated by Django 6.0.7 on 2026-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=60),
        ),
    ]
