# Generated by Django 6.0.7 on 2026-07-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0003_alter_booking_bookingdate_alter_booking_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='availableSystems',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='totalSystem',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Users'),
        ),
    ]
