# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0005_category_image_url_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Gamer / Customer'), ('provider', 'Gaming Center Provider')], db_index=True, default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=120)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='sparkzoneapp.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='sparkzoneapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='sparkzoneapp.providerprofile'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotDate', models.DateField(db_index=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('bookedCount', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Fully Booked'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sparkzoneapp.game')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='sparkzoneapp.slot'),
        ),
    ]
