# Generated by Django 6.0.7 on 2026-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0006_game_status_user_role_providerprofile_game_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
