# Generated by Django 6.0.7 on 2026-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0008_booking_notes_booking_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='operating_hours',
            field=models.CharField(blank=True, default='09:00 AM - 10:00 PM', max_length=100, null=True),
        ),
    ]
