# Generated by Django 6.0.7 on 2026-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0009_game_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='available_games',
            field=models.TextField(blank=True, help_text='Comma-separated names of games available at this station', null=True),
        ),
    ]
