# Generated by Django 6.0.7 on 2026-08-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0010_game_available_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unit_number',
            field=models.IntegerField(blank=True, help_text='Specific unit/console number (1..N)', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
