# Generated by Django 6.0.7 on 2026-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0011_booking_unit_number_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unit_numbers',
            field=models.CharField(blank=True, help_text='Comma-separated unit numbers e.g. 4,5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='out_of_service_units',
            field=models.CharField(blank=True, help_text='Comma-separated unit numbers out of service e.g. 2,5', max_length=255, null=True),
        ),
    ]
