# Generated by Django 6.0.7 on 2026-09-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkzoneapp', '0012_booking_unit_numbers_game_out_of_service_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid_online', 'Paid Online'), ('pay_at_venue', 'Pay at Venue'), ('refunded', 'Refunded'), ('pending', 'Pending Payment')], db_index=True, default='paid_online', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='cpu',
            field=models.CharField(blank=True, help_text='e.g. Intel Core i9-14900K / Ryzen 7 7800X3D', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='display_specs',
            field=models.CharField(blank=True, help_text='e.g. 27-inch 360Hz Fast-IPS / 4K 120Hz OLED', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='gpu',
            field=models.CharField(blank=True, help_text='e.g. NVIDIA RTX 4090 24GB', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='peripherals',
            field=models.TextField(blank=True, help_text='Headsets, keyboards, mice, steering wheels, sim pedals', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ram',
            field=models.CharField(blank=True, help_text='e.g. 32GB DDR5 6000MHz', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='sparkzoneapp.booking'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='is_verified_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed (Instant Lock)'), ('pending', 'Pending Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-Show')], db_index=True, default='confirmed', max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('razorpay', 'Razorpay Online'), ('pay_at_venue', 'Pay at Venue (Cash/Card)'), ('credit_card', 'Credit Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('debit_card', 'Debit Card'), ('other', 'Other')], db_index=True, default='razorpay', max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=60),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Fully Booked'), ('blocked', 'Blocked / Maintenance'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='FavoriteVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='sparkzoneapp.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stations', to='sparkzoneapp.user')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
